### ISSUE TITLE
sum(file.nevents) returns scientific notation

### ISSUE THREAD

**Issue by kpedro88** [dmwm/dasgoclient#36] opened 2022-07-06 07:36 UTC
Related to #5 but with a slightly different query:
```
dasgoclient -query="file dataset=/MET/Run2016B-ver2_HIPM_UL2016_MiniAODv2-v2/MINIAOD | sum(file.nevents)"
```
returns
```
sum(file.nevents): 3.5987712e+07
```

Interestingly, adding the `-json` flag returns:
```
[
{"das":{"expire":1657092121,"instance":"prod/global","primary_key":"file.name","record":1,"services":["dbs3:files_via_dataset"]},"function":"sum","key":"file.nevents","result":{"value":35987712}}
]
```

It would be easier to handle the output if it were in integer format consistently rather than scientific notation.

**Comment by vkuznet** [comment] 2022-07-06 19:14
The issue is fixed in https://github.com/dmwm/dasgoclient/releases/tag/v02.04.49 release, you may grab it directly from github or wait until CMSSW will make a new release. I'll post corresponding issue once I"ll make a build request.

**Comment by vkuznet** [comment] 2022-07-06 19:21
Now you can track the changes in CMSSW too. I'm closing this ticket now.

**Closed by vkuznet** 2022-07-06 19:21 UTC
